config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: [:create, :index]
      end
    end
  end
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    # Define User abilities
    if user.is? :admin
      can :manage, :all
    elsif user.is? :default
      can :read, Post
      can :manage, Post, author: user
      can :create, Comment
      can %i[read destroy], Comment, user_id: user.id
      can :manage, Comment, post: { author: user }
    else
      can :read, Post
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  def update_comments_counter
    post.increment!(:comments_counter)
  end

  after_save :update_comments_counter
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  def update_post_likes_counter
    post.increment!(:likes_counter)
  end

  after_save :update_post_likes_counter
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :title, presence: true, length: { in: 2..250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_posts_counter
    author.increment!(:posts_counter)
  end
  after_save :update_posts_counter
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :posts, foreign_key: 'author_id'
  has_many :likes

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_user_and_post

  def index
    @comments = @post.comments
    render json: @comments
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = @user

    if @comment.save
      render json: @comment, status: :created
    else
      render json: { errors: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def set_user_and_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    current_user = User.find(params[:user_id])
    posts = current_user.posts
    render json: posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html { redirect_to root_url, alert: exception.message }
      format.json { render json: { error: exception.message }, status: :forbidden }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user_and_post

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post = @post

    if @comment.save
      flash[:notice] = 'Comment created successfully'
    else
      flash[:alert] = 'Comment has to have at least two letters'
    end
    redirect_to user_post_path(@user, @post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to user_post_path(@user, @post)
  end

  private

  def set_user_and_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_user_and_post

  def create
    @like = current_user.likes.new
    @like.post = @post

    return unless @like.save

    redirect_to user_post_path(@user, @post)
  end

  private

  def set_user_and_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @pagy, @posts = pagy(@user.posts, items: 2)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to user_posts_path(current_user), notice: 'Post created succesfully'
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/comments/_form.html.erb
<%= form_with model: [@post, Comment.new], url: user_post_comments_path(@user, @post), remote: true do |f| %>
 <div class="flex gap-2">
  <div> <%= f.text_field :text, placeholder: 'Add a comment', minlength: 3 %></div>
 <button class="px-4 py-2 rounded font-bold bg-blue-500 text-white mb-4 w-fit hover:bg-blue-700"><%= f.submit 'Submit' %></button>
 </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with model: [@post, Like.new], url: user_post_likes_path(@user, @post), remote: true do |f| %>
 <button class="px-4 py-2 rounded font-bold bg-blue-500 text-white mb-4 w-fit hover:bg-blue-700"><%= f.submit 'Like' %></button>
<% end %>

app/views/posts/index.html.erb
<div class="flex flex-col items-center w-full">
  <div class="flex bg-blue-300 mb-4 w-full p-2 gap-2 border-2 text-black rounded transform hover:-translate-y-1 hover:-translate-x-1 transition-transform duration-200">
    <figure class="flex border border-black h-full">
     <% if @user.photo? %>
      <%= image_tag @user.photo, class: 'w-32 h-32 object-fill' %>
    <% else %>
      <p class="flex items-center justify-center w-32 h-32"></p>
    <% end %></figure>
    <div class="flex justify-between items-center w-full cursor-pointer">
      <div class="text-4xl">
        <%= @user.name %>
      </div>
      <div class="self-end">
        Number of posts: <%= @user.posts_counter.nil? ? 0 : @user.posts_counter %>
      </div>
    </div>
  </div>

  <%= link_to "Add new post", new_user_post_path(@user), class:"px-4 py-2 rounded font-bold bg-blue-500 text-white mb-4 hover:bg-blue-700"%>

  <% @posts.each do |post| %>
    <div class="w-full bg-blue-200 p-6 rounded-lg shadow-md mb-4 transform hover:-translate-y-1 hover:-translate-x-1 transition-transform duration-200">
      <%= link_to user_post_path(@user, post), class: "flex flex-col" do %>
        <h2 class="text-xl font-semibold mb-2"><%= post.title %></h2>
        <p><%= post.text %></p>
        <p class="self-end text-gray-600">Comments: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %></p>
      <% end %>
      
      <div class="mt-4">
        <% post.recent_comments.each do |comment| %>
          <div class="bg-gray-100 p-3 rounded-md mb-2">
            <p class="text-sm text-gray-700"><%= comment.user.name %> <%= comment.text %></p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class='flex items-center'>
  <%== pagy_nav(@pagy, link_extra: 'class="inline-block mx-2 px-3 border rounded-lg bg-white text-blue-500"') if @pagy.pages > 1 %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="flex flex-col items-start">
  <h1 class="text-4xl mb-4">Create new post</h1>
  <%= form_with model: @post, url: user_posts_path do |f| %>
    <div class="w-full max-w-md flex flex-col space-y-6">
      <div><%= f.text_field :title, placeholder: "Add title" %></div>
      <div><%= f.text_area :text, size: "60x10", placeholder: "Add text" %></div>
      <div class="px-4 py-2 rounded font-bold bg-blue-500 text-white mb-4 w-fit hover:bg-blue-700"><%= f.submit "Add new post" %></div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="flex flex-col items-center w-full bg-blue-300 p-2 rounded mb-4">
  <div class="w-full flex flex-col bg-blue-200 p-6 rounded-lg shadow-md mb-4">
    <h1 class="text-2xl font-semibold text-blue-500 mb-2"><%= @post.title %> by <%= @post.author.name %></h1>
    <p class="self-end text-gray-600">Comments: <%= @post.comments_counter || 0 %>, Likes: <%= @post.likes_counter || 0 %></p>

    <p class="mt-4"><%= @post.text %></p>
  </div>

  <% if @comments.present? %>
   <% @comments.each do |comment| %>
    <div class="flex justify-between w-full bg-gray-100 p-3 rounded-md mb-2">
      <p class="text-sm text-gray-700"><%= comment.user.name %>: <%= comment.text %></p>
      <% if can? :destroy, comment%>
      <div class="text-sm text-red-600">
      <%= button_to "Delete", user_post_comment_path(@user, @post, comment), method: :delete,form: {data: {turbo_confirm: 'Are you sure?'}}%>
      </div>
      <% end %>
    </div>
    <% end %>
  <% else %>
   <div class="w-full bg-gray-100 p-3 rounded-md mb-2">
    <p class="text-sm text-gray-700">No comments yet.</p>
   </div>
  <% end %>
  <div class="w-full flex justify-between">
   <%= render partial: 'comments/form', locals: { user: @post.author, post: @post } %>

   <%= render partial: 'likes/form', locals:{user: @post.author, post: @post}%>
  </div>
  <% if can? :destroy, @post%>
   <div class="text-sm bg-red-600 text-white px-4 py-2 rounded-lg">
      <%= button_to "Delete", user_post_path(@post), method: :delete,form: {data: {turbo_confirm: 'Are you sure?'}}%>
   </div>
   <% end %>
 </div>

app/views/users/index.html.erb
<div class="fixed top-0 left-0 p-5">
  <%= button_to "Logout", destroy_user_session_path, method: :delete %>
</div>

<div class="flex flex-col gap-1 w-full">
<% @users.each do |user| %>
  <%= link_to user_path(user), class: 'flex gap-4 mb-4 p-2 bg-blue-300 text-black border-2 border-black rounded' do %>
    <figure class="flex border border-black h-full">
     <% if user.photo? %>
      <%= image_tag user.photo, class: 'w-32 h-32 object-fill' %>
    <% else %>
      <p class="flex items-center justify-center w-32 h-32"></p>
    <% end %></figure>
    <div class="flex justify-between items-center w-full">
    <div class="text-4xl">
      <%= user.name %>
    </div>
    <div class="self-end">
      Number of posts: <%= user.posts_counter.nil? ? 0 : user.posts_counter %>
    </div>
    </div >
  <% end %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="flex flex-col items-center w-full">
<div class="flex bg-blue-300 mb-4 w-full p-2 gap-2 border-2 border-blue-400 transform hover:-translate-y-1 hover:-translate-x-1 transition-transform duration-200">
  <figure class="flex border border-black h-full">
     <% if @user.photo? %>
      <%= image_tag @user.photo, class: 'w-32 h-32 object-fill' %>
    <% else %>
      <p class="flex items-center justify-center w-32 h-32"></p>
    <% end %></figure>
    <div class="flex justify-between items-center w-full cursor-pointer">
    <div class="text-4xl text-black">
      <%= @user.name %>
    </div>
    <div class="text-black self-end">
      Number of posts: <%= @user.posts_counter.nil? ? 0 : @user.posts_counter %>
    </div>
    </div >
</div>

<div class="flex w-full flex-col border-2 border-blue-400 mb-4 p-2 cursor-pointer transform hover:-translate-y-1 hover:-translate-x-1 transition-transform duration-200">
<h1 class="text-2xl font-bold mb-2">Bio</h1>
<p class=""><%= @user.bio %></p>
</div>

<% @user.recent_posts.each do |post| %>
  <%= link_to user_post_path(@user, post), class: 'flex flex-col mb-4 p-4 bg-blue-100 transform hover:-translate-y-1 hover:-translate-x-1 transition-transform duration-200 rounded w-full' do %>
    <div class="font-bold text-lg mb-2">
      <%= post.title %>
    </div>
    <div class="text-gray-900">
      <%= post.text %>
    </div>
    <p class="flex text-gray-500 mt-2 justify-end">
      Number of comments: <%= post.comments_counter || 0 %>, Number of likes: <%= post.likes_counter || 0 %> 
    </p>
  <% end %>
<% end %>

<%= link_to "See all posts", user_posts_path(@user), class: 'px-4 py-2 rounded font-bold bg-blue-500 text-white mb-4 hover:bg-blue-700' %>
</div>